### ISSUE TITLE
How can I use this project in Docker?

### ISSUE THREAD

**Issue by Uber-Eins** [fernvenue/adguard-home-upstream#3]

**Comment by fernvenue** [comment]
Hi, I don't use Docker at all, because it override users iptables/firewall rules by default, and some other resons like that makes me don't like it, so the answer is: I don't know, but feel free to fork this project and make any appropriate changes within the scope allowed by the license for your own scenario like running in Docker or something else.

By the way, if you successfully run this project inside the Docker, maybe write it down here will be helpful for some people wanna run this in Docker like you :)

**Comment by Uber-Eins** [comment]
> Hi, I don't use Docker at all, because it override users iptables/firewall rules by default, and some other resons like that makes me don't like it, so the answer is: I don't know, but feel free to fork this project and make any appropriate changes within the scope allowed by the license for your own scenario like running in Docker or something else.
> 
> By the way, if you successfully run this project inside the Docker, maybe write it down here will be helpful for some people wanna run this in Docker like you :)

I did it
Just need to modify the upstream.sh file and rebuild AdGuardHome.
Change `systemctl restart AdGuardHome` to `docker restart AdguardHome`

Compose example
```
version: '3'
services:
  adguardhome:
    container_name: AdguardHome
    restart: always
    network_mode: host
    volumes:
      - ./data/work:/opt/adguardhome/work
      - ./data/conf:/opt/adguardhome/conf
      - /usr/share/adguardhome.upstream:/usr/share/adguardhome.upstream
    image: adguard/adguardhome:v0.107.41
```
